### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by LucifersChild** [qubard/ChessKurwa#2]
Can't for the life of me figure out how to make this work think you could upload a private video on youtube with a tutorial or maybe help me with teamviewer?

**Comment by qubard** [comment]
Hi, download the project and open it up in an IDE (I use Eclipse) and set it up to look like [this](http://upload.blueberrypancak.es/HSvVJls.png) (make sure you download the latest version of Stockfish). Start it by running main in Main.java. The README will then tell you what to make your board look like to get it to recognize the board.

You can get Eclipse [here](http://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/mars2) and Stockfish [here](https://stockfishchess.org/). 

Beyond this since I haven't received more than enough complaints to warrant a tutorial ;p.

**Comment by qubard** [comment]
Hey, sorry, there may have been in fact a bug with the bot when this issue was posted. I was not able to check because Chess.com rolled out an update where the black knight changed its color a bit and siding was changed slightly. The current release should work.
